# Generated by Django 4.2.23 on 2025-06-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('desert', 'Desert'), ('drink', 'Drink'), ('side', 'Side')], default='starter', max_length=25)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
