# Generated by Django 4.2.23 on 2025-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('allergy_labels', models.CharField(choices=[('contains dairy', 'Contains Dairy'), ('contains nuts', 'Contains Nuts'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten free', 'Gluten Free')], default=None, max_length=50)),
                ('contains_dairy', models.BooleanField(default=False)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
            ],
        ),
    ]
