# Generated by Django 4.2.23 on 2025-07-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_allergylabels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('sides', 'Sides'), ('salads', 'Salads'), ('drinks', 'Drinks'), ('desserts', 'Desserts'), ('chefs special', "Chef's Special")], default='starter', max_length=50)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
